version: '2'

services:
  app:
    image: saleschamp/php
    working_dir: ${PWD}
    command: php -S 0.0.0.0:8080 -t public public/index.php
    environment:
      - docker=true
      # Put the definition in .env file
      - COMPOSER_AUTH
    ports:
      - 8080:8080
    volumes:
      - .:${PWD}
      - logs:${PWD}/logs

volumes:
  logs:
    driver: local
