version: '2'

volumes:
  logs:
    driver: local

services:
  app:
    image: saleschamp/php
    working_dir: /var/www/public
    command: php-fpm
    environment:
      docker: "true"
    volumes:
      - .:/var/www
      - logs:/var/www/logs

  www:
    image: nginx:1.13
    volumes:
      - ./www/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
